### ISSUE TITLE
How to use the package

### ISSUE THREAD

**Issue by alaadahmed** [tmbb/mezzofanti#10]
I am sorry to raise an issue about how to use the package, but really documentation or README file is somehow poor and doesn't provide rich information on how to use it, I knew by trying that there is a command `mix i18n.extract`. It created `messages.json` file for me, but what then? how to fill that file with translation for two other locales different than `"en"`. How to use __plural__, 
```json
{
  "deleted_messages": [],
  "locales": [
    "ar",
    "de"
  ],
  "messages": [
    {
      "context": "",
      "domain": "ahram_school_web.post_live",
      "locations": [
        {
          "file": "lib/ahram_school_web/live/pages/blog/post_live.html.leex",
          "line": 43,
          "module": "Elixir.AhramSchoolWeb.PostLive"
        }
      ],
      "text": "{count} minute read",
      "translations": [
        {
          "locale": "ar",
          "=0": "ثواني قراءة",
          "=1": "دقيقة واحدة قراءة",
          "=2": "دقيقتين قراءة",
          "=3": "{count} دقائق قراءة",
          "=4": "{count} دقيقة قراءة",
          "=5": "{count} دقيقة قراءة"
        }
      ]
    }
  ]
}
```
I use it inside __PhoenixLiveView__ in `.leex` file like so: 
`<%= I18n.t("{count} minute read", count: read_time(post.content), locale: @locale)  %>`

I am sorry again for that kind of issue, but I couldn't figure out how to use it.

**Comment by tmbb** [comment]
There are still some things to iron out and the docs aren't complete yet. You're not supposed to be able to run it without understanding the source code yet.
