### ISSUE TITLE
Does it make sense to keep a Mezzofanti locale separate from the CLDR locale?

### ISSUE THREAD

**Issue by tmbb** [tmbb/mezzofanti#3]
Does it make sense to keep a Mezzofanti locale separate from the CLDR locale? If the only thing I'm doing with the Mezzofanti locale is feeding it into CLDR, shouldn't we use the CLDR locale directly and get rid of yet another incompatible locale?

**Comment by kipcole9** [comment]
I had the same thought. I think it makes sense to use the same locale. The CLDR locale also knows about Gettext so it keeps everything tied together quite cleanly.

**Comment by tmbb** [comment]
In the [CLDR docs](https://hexdocs.pm/ex_cldr/Cldr.html#put_locale/1) (and in function's spec) it says that `Cldr.put_locale()` supports string locales, but the actual code requires a [%Cldr.LanguageTag{}](https://github.com/elixir-cldr/cldr/blob/v2.17.0/lib/cldr.ex#L312). I

**Comment by kipcole9** [comment]
Good callout. There's some historical issues here that I can cleanup now that each `Cldr.LanguageTag.t` knows which backend it was defined in.

The current design allows for each backend to have a per-process current locale. But that doesn't really make sense any more - a process should have a current locale, irrespective of which backend it is defined upon. 

I will make those changes, confirm there aren't any regressions, and publish an update.

**Comment by kipcole9** [comment]
As of [this commit](https://github.com/elixir-cldr/cldr/commit/173214dbc278cdcf18a6ce395dae6d60a6b17930), `Cldr.put_locale/{1, 2}` now stores one locale per Process, not one locale per backend per process. This is much cleaner than the old model and is possible now that language tags know the locale that can support them.

The commit is on the [CLDR38 branch](https://github.com/elixir-cldr/cldr/tree/cldr38) which is in preparation for [Unicode CLDR38](http://cldr.unicode.org/index/downloads/cldr-38) that will ship in October. 

You are welcome to try that branch. I haven't tested it yet against the other libs that depend upon it though (its getting late here and I will do the testing tomorrow).

**Comment by tmbb** [comment]
Mezzofanti nos uses the Cldr locale everywhere.
