### ISSUE TITLE
Translations file name resolution

### ISSUE THREAD

**Issue by kipcole9** [tmbb/mezzofanti#5]
One area for consideration is resolving the translations file name and translations locale. Assuming for the moment you choose to standardise on the CLDR locale then the relevant standards around locale naming mean that it may make sense to consider a more flexible translation locale matching algorithm.

For example, `pt-BR`, `pt_br` and `PT-BR` are all semantically the same.  CLDR chooses to use a canonical format which is `pt-BR`.  So if CLDR becomes the standard locale for Mezzofanti then its reasonably straight forward to document the requirement that the `*.pot` file name (and therefore locale) should be the same as the `cldr_locale_name` element in a `Cldr.LanguageTag.t`.

Should there also be fallbacks?  If the locale is `pt-PT`, should translations fall back to `pt` if there is none satisfied by the `pt-PT` translations?

**Comment by tmbb** [comment]
> Should there also be fallbacks? If the locale is pt-PT, should translations fall back to pt if there is none satisfied by the pt-PT translations

I don't think there should be any fallbacks at this level. If there CLDR is meant to support fallbacks it should do that at a higher level and not when looking up the available language directories.

**Comment by kipcole9** [comment]
Yes, I think you're right. That makes sense.
